import type { ImageSourcePropType } from "react-native";

import { monitoring } from "@/lib/monitoring";

import { THEMES } from "./themes";

/**
 * Per-theme alternate app icons.
 *
 * Each icon is the same Future Self mark, full-bleed, on that theme's
 * fill (no inset cream tile / extra border). Generated by
 * `scripts/generate-app-icons.mjs` into `assets/icons/icon-<id>.png`
 * plus `-dark` / `-tinted` companions, registered with the
 * expo-alternate-app-icons config plugin in app.json under the
 * PascalCase name (`minimal_sand` -> `MinimalSand`).
 *
 * The bundled primary icon (`expo.icon`) IS the Minimal Sand look, so
 * "no alternate set" reads as `minimal_sand`. The picker preview for
 * that tile uses `assets/images/icon.png` — the same file iOS puts on
 * the Home Screen — rather than a generated copy that used to show a
 * lighter sand frame the real icon does not have.
 *
 * Soft Bloom is not offered (TestFlight, Sep 2026). Inkwell, Arctic and
 * Sun are. Retired ids still resolve so a leftover Home Screen icon
 * can be reset to the default.
 *
 * iOS shows a system alert every time the icon changes. The onboarding
 * picker and the Themes screen both apply on tap (debounced in the
 * picker); onboarding completion re-applies as a safety net, which is a
 * no-op once the icon is already active.
 */

/** Theme id whose icon is the bundled primary icon (`expo.icon`). */
export const DEFAULT_APP_ICON_ID = "minimal_sand";

/** Alternate icons no longer offered; mapped back to the default. */
export const RETIRED_APP_ICON_IDS = new Set(["soft_bloom"]);

/**
 * Icon ids in picker order. Independent of THEMES order so the grid
 * can list Inkwell / Arctic / Sun without Soft Bloom, and keep
 * Terracotta next to the dark set.
 */
export const APP_ICON_IDS: string[] = [
  "minimal_sand",
  "ocean_clarity",
  "terracotta",
  "midnight_focus",
  "ink_well",
  "arctic",
  "sun",
  "sunrise_momentum",
  "golden_success",
  "evergreen",
];

/**
 * Bundled previews for the pickers. Static `require` literals so Metro
 * packages every remaining icon; keys must stay in lockstep with
 * APP_ICON_IDS (guarded by `src/__tests__/appIcons.test.ts`).
 */
export const APP_ICON_SOURCES: Record<string, ImageSourcePropType> = {
  // Primary Home Screen icon — not the generated Minimal Sand PNG.
  minimal_sand: require("../../assets/images/icon.png"),
  ocean_clarity: require("../../assets/icons/icon-ocean_clarity.png"),
  terracotta: require("../../assets/icons/icon-terracotta.png"),
  midnight_focus: require("../../assets/icons/icon-midnight_focus.png"),
  ink_well: require("../../assets/icons/icon-ink_well.png"),
  arctic: require("../../assets/icons/icon-arctic.png"),
  sun: require("../../assets/icons/icon-sun.png"),
  sunrise_momentum: require("../../assets/icons/icon-sunrise_momentum.png"),
  golden_success: require("../../assets/icons/icon-golden_success.png"),
  evergreen: require("../../assets/icons/icon-evergreen.png"),
};

/**
 * The alternate-icon name registered for a theme id. Mirrors the
 * plugin's PascalCase conversion (`sunrise_momentum` -> `SunriseMomentum`).
 */
export function appIconNameFor(id: string): string {
  return id
    .split(/[\s\-_]+/)
    .filter(Boolean)
    .map((word) => word[0]!.toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

const KNOWN_ICON_IDS: string[] = THEMES.map((t) => t.id);

/** Inverse of `appIconNameFor`; `null` (primary icon) and unknown names map to the default. */
export function appIconIdFromName(name: string | null): string {
  if (!name) return DEFAULT_APP_ICON_ID;
  return (
    KNOWN_ICON_IDS.find((id) => appIconNameFor(id) === name) ??
    DEFAULT_APP_ICON_ID
  );
}

/** Retired or missing ids become the bundled primary icon. */
export function resolveAppIconId(id: string | null): string {
  if (!id || RETIRED_APP_ICON_IDS.has(id)) return DEFAULT_APP_ICON_ID;
  return id;
}

type AlternateAppIconsModule = typeof import("expo-alternate-app-icons");

let nativeModule: AlternateAppIconsModule | null | undefined;

/**
 * Loads expo-alternate-app-icons lazily: its top level resolves the
 * native module, which is absent in Jest, Expo Go and on the web. A
 * missing module means "icons can't change here", never a crash.
 */
function alternateIcons(): AlternateAppIconsModule | null {
  if (nativeModule !== undefined) return nativeModule;
  try {
    // Deferred (not a static import) so environments without the native
    // module still boot; the failure is cached and treated as "unsupported".
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const loaded = require("expo-alternate-app-icons");
    nativeModule = loaded as AlternateAppIconsModule;
  } catch {
    nativeModule = null;
  }
  return nativeModule;
}

/** The theme id whose icon is currently on the Home Screen. */
export function getCurrentAppIconId(): string {
  try {
    const icons = alternateIcons();
    if (!icons?.supportsAlternateIcons) return DEFAULT_APP_ICON_ID;
    return resolveAppIconId(appIconIdFromName(icons.getAppIconName()));
  } catch {
    return DEFAULT_APP_ICON_ID;
  }
}

/**
 * Switches the Home Screen icon to the given theme's icon (`null` ->
 * default). Already active is a no-op, so a user who keeps the default
 * never sees the iOS "changed the icon" alert. The default (Minimal
 * Sand) is the bundled primary icon, so choosing it *resets* the
 * alternate icon (`setAlternateAppIcon(null)`) instead of selecting an
 * alternate by name. Retired icons (Soft Bloom) reset to the default.
 *
 * Resolves `true` when the Home Screen now shows the requested icon
 * (applied or already active) and `false` when it could not be changed
 * (unsupported device, unknown id, native failure). Never throws; the
 * failure is reported to monitoring and, in development, logged.
 */
export async function applyAppIcon(id: string | null): Promise<boolean> {
  const target = resolveAppIconId(id);
  if (!APP_ICON_IDS.includes(target)) return false;
  try {
    const icons = alternateIcons();
    if (!icons?.supportsAlternateIcons) return false;
    if (appIconIdFromName(icons.getAppIconName()) === target) return true;
    await icons.setAlternateAppIcon(
      target === DEFAULT_APP_ICON_ID ? null : appIconNameFor(target),
    );
    return true;
  } catch (error) {
    if (__DEV__) console.warn(`[appIcon] could not apply "${target}"`, error);
    monitoring.captureError(error, { area: "appIcon.apply", icon: target });
    return false;
  }
}
