import type { ImageSourcePropType } from "react-native";

import { monitoring } from "@/lib/monitoring";

import { THEMES } from "./themes";

/**
 * Per-theme alternate app icons.
 *
 * One icon per theme id, generated by `scripts/generate-app-icons.mjs`
 * into `assets/icons/icon-<id>.png` and registered with the
 * expo-alternate-app-icons config plugin in app.json under the
 * PascalCase name (`minimal_sand` -> `MinimalSand`) the plugin uses for
 * the asset catalogue. The bundled primary icon (`expo.icon`) is the
 * Minimal Sand look, so "no alternate set" reads as `minimal_sand`.
 *
 * iOS shows a system alert every time the icon changes, so callers
 * decide *when* to apply: onboarding records the choice and applies it
 * once at completion; the Themes screen applies on tap.
 */

/** Theme id whose icon is the bundled primary icon (`expo.icon`). */
export const DEFAULT_APP_ICON_ID = "minimal_sand";

/** Icon ids, in theme order — the picker grid order. */
export const APP_ICON_IDS: string[] = THEMES.map((t) => t.id);

/**
 * Bundled previews for the pickers. Static `require` literals so Metro
 * packages every icon; keys must stay in lockstep with THEMES ids
 * (guarded by `src/__tests__/appIcons.test.ts`).
 */
export const APP_ICON_SOURCES: Record<string, ImageSourcePropType> = {
  minimal_sand: require("../../assets/icons/icon-minimal_sand.png"),
  soft_bloom: require("../../assets/icons/icon-soft_bloom.png"),
  ocean_clarity: require("../../assets/icons/icon-ocean_clarity.png"),
  midnight_focus: require("../../assets/icons/icon-midnight_focus.png"),
  ink_well: require("../../assets/icons/icon-ink_well.png"),
  sunrise_momentum: require("../../assets/icons/icon-sunrise_momentum.png"),
  golden_success: require("../../assets/icons/icon-golden_success.png"),
  evergreen: require("../../assets/icons/icon-evergreen.png"),
  terracotta: require("../../assets/icons/icon-terracotta.png"),
  arctic: require("../../assets/icons/icon-arctic.png"),
};

/**
 * The alternate-icon name registered for a theme id. Mirrors the
 * plugin's PascalCase conversion (`sunrise_momentum` -> `SunriseMomentum`).
 */
export function appIconNameFor(id: string): string {
  return id
    .split(/[\s\-_]+/)
    .filter(Boolean)
    .map((word) => word[0]!.toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

/** Inverse of `appIconNameFor`; `null` (primary icon) and unknown names map to the default. */
export function appIconIdFromName(name: string | null): string {
  if (!name) return DEFAULT_APP_ICON_ID;
  return (
    APP_ICON_IDS.find((id) => appIconNameFor(id) === name) ??
    DEFAULT_APP_ICON_ID
  );
}

type AlternateAppIconsModule = typeof import("expo-alternate-app-icons");

let nativeModule: AlternateAppIconsModule | null | undefined;

/**
 * Loads expo-alternate-app-icons lazily: its top level resolves the
 * native module, which is absent in Jest, Expo Go and on the web. A
 * missing module means "icons can't change here", never a crash.
 */
function alternateIcons(): AlternateAppIconsModule | null {
  if (nativeModule !== undefined) return nativeModule;
  try {
    // Deferred (not a static import) so environments without the native
    // module still boot; the failure is cached and treated as "unsupported".
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const loaded = require("expo-alternate-app-icons");
    nativeModule = loaded as AlternateAppIconsModule;
  } catch {
    nativeModule = null;
  }
  return nativeModule;
}

/** The theme id whose icon is currently on the Home Screen. */
export function getCurrentAppIconId(): string {
  try {
    const icons = alternateIcons();
    if (!icons?.supportsAlternateIcons) return DEFAULT_APP_ICON_ID;
    return appIconIdFromName(icons.getAppIconName());
  } catch {
    return DEFAULT_APP_ICON_ID;
  }
}

/**
 * Switches the Home Screen icon to the given theme's icon (`null` ->
 * default). No-op when unsupported, unknown, or already active — so a
 * user who keeps the default never sees the iOS "changed the icon"
 * alert. Never throws.
 */
export async function applyAppIcon(id: string | null): Promise<void> {
  const target = id ?? DEFAULT_APP_ICON_ID;
  if (!APP_ICON_IDS.includes(target)) return;
  try {
    const icons = alternateIcons();
    if (!icons?.supportsAlternateIcons) return;
    if (appIconIdFromName(icons.getAppIconName()) === target) return;
    await icons.setAlternateAppIcon(appIconNameFor(target));
  } catch (error) {
    monitoring.captureError(error, { area: "appIcon.apply", icon: target });
  }
}
