import type { VariantConfig } from "../engine/types";

/**
 * iam-claude: Claude-original copy on the I Am UX framework.
 * Spec: docs/ONBOARDING_COPY_IAM_CLAUDE.md
 */
export const iamClaude: VariantConfig = {
  id: "iam-claude",
  family: "iam",
  paywallStyle: "timeline",
  paywallCloseDelayMs: 2000,
  authSheetBeforePaywall: false,
  steps: [
    {
      id: "welcome",
      type: "welcome",
      headline: "Become the person you keep promising yourself.",
      sub: "Future Self turns quotes and affirmations into small daily pushes toward the life you actually want.",
      cta: "Begin",
    },
    {
      id: "name",
      type: "text",
      headline: "What should we call you?",
      sub: "Your future self is going to address you by name",
      placeholder: "Your name",
      cta: "Continue",
      skippable: true,
      maxLength: 40,
      modelKey: "name",
    },
    {
      id: "age",
      type: "single",
      headline: (ctx) =>
        ctx.name ? `How old are you, ${ctx.name}?` : "How old are you?",
      sub: "We tune the voice to where you are in life",
      options: [
        { slug: "u18", label: "Under 18" },
        { slug: "18-24", label: "18 to 24" },
        { slug: "25-34", label: "25 to 34" },
        { slug: "35-44", label: "35 to 44" },
        { slug: "45-54", label: "45 to 54" },
        { slug: "55+", label: "55+" },
      ],
      skippable: true,
      modelKey: "raw.age_band",
    },
    {
      id: "motivation",
      type: "single",
      headline: "Where's your motivation right now?",
      sub: "Honest answer — it sets your starting pace",
      options: [
        { slug: "all-in", label: "Ready to change everything", emoji: "🔥" },
        {
          slug: "inconsistent",
          label: "Motivated, but inconsistent",
          emoji: "📈",
        },
        { slug: "empty", label: "Running on empty", emoji: "🌫️" },
        { slug: "unsure", label: "Honestly, I'm not sure", emoji: "🤍" },
      ],
      modelKey: "motivation_level",
    },
    {
      id: "gap-interstitial",
      type: "info",
      headline:
        "The person you'll be in five years is being built in the ordinary hours of today.",
      cta: "Continue",
    },
    {
      id: "goals",
      type: "multi",
      headline: "What matters most to you right now?",
      sub: "Choose up to three — they shape your daily mix",
      maxSelect: 3,
      minSelect: 1,
      options: [
        { slug: "discipline", label: "Discipline & consistency", emoji: "💪" },
        { slug: "confidence", label: "Confidence & self-belief", emoji: "🧠" },
        { slug: "body", label: "Health & energy", emoji: "🩺" },
        { slug: "career", label: "Career & money", emoji: "💼" },
        { slug: "relationships", label: "Relationships", emoji: "❤️" },
        { slug: "peace", label: "Peace of mind", emoji: "🕊️" },
        { slug: "purpose", label: "Purpose & direction", emoji: "🧭" },
      ],
      skippable: true,
      modelKey: "primary_goals",
    },
    {
      id: "obstacles",
      type: "multi",
      headline: "And what keeps getting in the way?",
      sub: "Naming it is the first push",
      minSelect: 1,
      options: [
        { slug: "procrastination", label: "I put things off", emoji: "⏳" },
        { slug: "distraction", label: "My phone eats my day", emoji: "📱" },
        { slug: "motivation", label: "I start strong, then stop", emoji: "🔁" },
        { slug: "overwhelm", label: "I get overwhelmed", emoji: "🌀" },
        { slug: "self-doubt", label: "I doubt myself", emoji: "🪞" },
        { slug: "no-plan", label: "I don't have a clear plan", emoji: "🗺️" },
      ],
      skippable: true,
      modelKey: "obstacles",
    },
    {
      id: "system-interstitial",
      type: "info",
      headline:
        "Consistency isn't a personality trait. It's a system — and you're about to build one.",
      cta: "Continue",
    },
    {
      id: "traits",
      type: "chips",
      headline: "Meet your future self. What are they like?",
      sub: "Pick the traits you're building toward",
      maxSelect: 4,
      minSelect: 1,
      options: [
        { slug: "disciplined", label: "Disciplined" },
        { slug: "confident", label: "Confident" },
        { slug: "calm", label: "Calm" },
        { slug: "strong", label: "Strong" },
        { slug: "focused", label: "Focused" },
        { slug: "free", label: "Free" },
        { slug: "generous", label: "Generous" },
        { slug: "fulfilled", label: "Fulfilled" },
      ],
      skippable: true,
      modelKey: "future_traits",
    },
    {
      id: "life-goal",
      type: "text",
      headline: "Finish the sentence: a year from now, I want to be…",
      sub: "Your words. They'll follow you through the app — and onto your Home Screen if you want.",
      placeholder: "…someone who shows up every single day",
      multiline: true,
      maxLength: 280,
      cta: "Save it",
      skippable: true,
      modelKey: "life_goal",
    },
    {
      id: "notifications",
      type: "notifications",
      headline: "This is how you won't drift.",
      sub: "Future Self finds you through the day with the right words. You control how often, and when.",
      cta: "Allow and Save",
      mockLine: "Discipline is remembering what you want.",
    },
    {
      id: "streak",
      type: "streak-commit",
      headline: "Three small readings a day. That's the whole ask.",
      sub: "Read any 3 quotes or affirmations and the day counts. Miss a day, the chain breaks.",
      options: [
        { slug: "3", label: "3 days to start" },
        { slug: "7", label: "7 days in a row" },
        { slug: "21", label: "21 days — a real habit" },
      ],
      cta: "Commit",
      modelKey: "raw.streak_goal",
    },
    {
      id: "quote-topics",
      type: "chips",
      headline: "Which voices push you hardest?",
      sub: "We'll weight your daily quotes toward these",
      minSelect: 1,
      options: [
        { slug: "discipline", label: "Discipline" },
        { slug: "ambition", label: "Ambition" },
        { slug: "courage", label: "Courage" },
        { slug: "stoic-calm", label: "Stoic calm" },
        { slug: "gratitude", label: "Gratitude" },
        { slug: "resilience", label: "Resilience" },
        { slug: "focus", label: "Focus" },
        { slug: "kindness", label: "Kindness" },
      ],
      skippable: true,
      modelKey: "quote_interests",
    },
    {
      id: "affirmation-topics",
      type: "chips",
      headline: "And what do you need to hear more often?",
      sub: "Your affirmations will lean this way",
      minSelect: 1,
      options: [
        { slug: "self-belief", label: "Self-belief" },
        { slug: "calm", label: "Calm under pressure" },
        { slug: "health-body", label: "Health & body" },
        { slug: "abundance", label: "Abundance" },
        { slug: "letting-go", label: "Letting go" },
        { slug: "morning-energy", label: "Morning energy" },
        { slug: "boundaries", label: "Boundaries" },
        { slug: "self-respect", label: "Self-respect" },
      ],
      skippable: true,
      trialCaption: true,
      modelKey: "affirmation_interests",
    },
    {
      id: "theme",
      type: "theme",
      headline: "Choose how your words should look.",
      sub: "You can change this anytime — or build your own",
      trialCaption: true,
      cta: "Continue",
    },
    {
      id: "result",
      type: "result",
      cta: "Sounds right",
    },
    {
      id: "source",
      type: "single",
      headline: "One last thing — how did you find us?",
      sub: "It helps a small team keep showing up there",
      options: [
        { slug: "web", label: "Web search" },
        { slug: "app-store", label: "App Store" },
        { slug: "friend", label: "Friend or family" },
        { slug: "tiktok", label: "TikTok" },
        { slug: "instagram", label: "Instagram" },
        { slug: "other", label: "Other" },
      ],
      skippable: true,
      modelKey: "raw.source",
    },
    {
      id: "trial-preframe",
      type: "info",
      headline: (ctx) =>
        ctx.trialLength
          ? `Everything unlocked, free for ${ctx.trialLength}.`
          : "Everything unlocked from day one.",
      sub: "No surprises: we'll remind you before the trial ends, and you can cancel anytime.",
      cta: "Show me how it works",
      condition: (ctx) => ctx.trialLength !== null,
    },
    {
      id: "paywall",
      type: "paywall",
    },
    {
      id: "widget-lock",
      type: "widget-promo",
      headline: "Put your future on your Lock Screen.",
      sub: "See your words without unlocking your phone",
      cta: "Got it",
      placeholder: "I will not waste today.",
    },
    {
      id: "widget-home",
      type: "widget-promo",
      headline: "One more: your Home Screen.",
      sub: "Touch and hold your Home Screen, tap Edit, and add Future Self",
      cta: "Set up widget",
      secondaryCta: "Later",
      placeholder: "A year from now, you'll be glad you started today.",
    },
  ],
};
