import type { VariantConfig } from "../engine/types";

/**
 * iam-claude: Claude-original copy on the I Am UX framework.
 * Spec: docs/ONBOARDING_COPY_IAM_CLAUDE.md
 *
 * Rhythm follows I Am: bursts of 2–4 quick taps, then a breather
 * (interstitial, notification config, streak visual, science/benefits).
 * Every `raw.*` key lands in raw_answers (Supabase only, never analytics).
 */
export const iamClaude: VariantConfig = {
  id: "iam-claude",
  family: "iam",
  paywallStyle: "timeline",
  paywallCloseDelayMs: 2000,
  authSheetBeforePaywall: false,
  steps: [
    {
      id: "welcome",
      type: "welcome",
      headline: "Become the person you keep promising yourself.",
      sub: "Future Self turns quotes and affirmations into small daily pushes toward the life you actually want.",
      cta: "Begin",
    },
    {
      id: "name",
      type: "text",
      headline: "What should we call you?",
      sub: "Your future self is going to address you by name",
      placeholder: "Your name",
      cta: "Continue",
      skippable: true,
      maxLength: 40,
      modelKey: "name",
    },
    {
      id: "age",
      type: "single",
      headline: (ctx) =>
        ctx.name ? `How old are you, ${ctx.name}?` : "How old are you?",
      sub: "Your age helps us personalize your quotes and affirmations",
      options: [
        { slug: "u18", label: "Under 18" },
        { slug: "18-24", label: "18 to 24" },
        { slug: "25-34", label: "25 to 34" },
        { slug: "35-44", label: "35 to 44" },
        { slug: "45-54", label: "45 to 54" },
        { slug: "55+", label: "55+" },
      ],
      skippable: true,
      modelKey: "raw.age_band",
    },
    {
      id: "motivation",
      type: "single",
      headline: "Where's your motivation right now?",
      sub: "Be honest — we'll meet you where you are",
      options: [
        { slug: "all-in", label: "Ready to change everything", emoji: "🔥" },
        {
          slug: "inconsistent",
          label: "Motivated, but inconsistent",
          emoji: "📈",
        },
        { slug: "empty", label: "Not motivated right now", emoji: "🌫️" },
        { slug: "unsure", label: "I'm not sure yet", emoji: "🤍" },
      ],
      modelKey: "motivation_level",
    },
    {
      id: "gap-interstitial",
      type: "info",
      headline:
        "The person you'll be in five years is being built in the ordinary hours of today.",
      cta: "Continue",
    },
    {
      id: "familiarity",
      type: "single",
      headline: (ctx) =>
        ctx.name
          ? `How familiar are you with affirmations, ${ctx.name}?`
          : "How familiar are you with affirmations?",
      sub: "Your answer shapes how we introduce them",
      options: [
        { slug: "new", label: "This is new for me" },
        { slug: "occasionally", label: "I've used them occasionally" },
        { slug: "regularly", label: "I use them regularly" },
      ],
      skippable: true,
      modelKey: "raw.affirmation_familiarity",
    },
    {
      id: "affirmations-intro",
      type: "info",
      headline:
        "Affirmations are short, positive statements you repeat to yourself — until they become how you think.",
      cta: "Continue",
      // Only newcomers get the primer — that is what makes the
      // familiarity sub ("shapes how we introduce them") honest.
      condition: (ctx) => ctx.answers["raw.affirmation_familiarity"] === "new",
    },
    {
      id: "habit-helper",
      type: "multi",
      headline: "What would help make affirmations a daily habit?",
      sub: "Choose all that apply",
      minSelect: 1,
      // Every option maps to a real Future Self feature.
      options: [
        { slug: "reminders", label: "Getting regular reminders" },
        { slug: "progress", label: "Tracking my progress" },
        { slug: "widget", label: "A Home or Lock Screen widget" },
        { slug: "fit", label: "Quotes that fit my goals" },
        { slug: "unsure", label: "I don't know yet" },
      ],
      skippable: true,
      modelKey: "raw.habit_helpers",
    },
    {
      id: "repetition",
      type: "info",
      headline:
        "Through daily repetition, you can change your beliefs and your mindset.",
      cta: "Continue",
    },
    {
      id: "notifications",
      type: "notifications",
      headline: "This is how you won't drift.",
      sub: "Future Self finds you through the day with the quotes you need to hear. You choose how often, and when.",
      cta: "Allow and Save",
      mockLine: "Discipline is remembering what you want.",
    },
    {
      id: "goals",
      type: "multi",
      headline: "What matters most to you right now?",
      sub: "Choose up to three — they shape your daily quotes and affirmations",
      maxSelect: 3,
      minSelect: 1,
      options: [
        { slug: "discipline", label: "Discipline & consistency", emoji: "💪" },
        { slug: "confidence", label: "Confidence & self-belief", emoji: "🧠" },
        { slug: "body", label: "Health & energy", emoji: "🩺" },
        { slug: "career", label: "Career & money", emoji: "💼" },
        { slug: "relationships", label: "Relationships", emoji: "❤️" },
        { slug: "peace", label: "Peace of mind", emoji: "🕊️" },
        { slug: "purpose", label: "Purpose & direction", emoji: "🧭" },
      ],
      skippable: true,
      modelKey: "primary_goals",
    },
    {
      id: "obstacles",
      type: "multi",
      headline: "And what keeps getting in the way?",
      sub: "Naming it is the first step",
      minSelect: 1,
      options: [
        { slug: "procrastination", label: "I put things off", emoji: "⏳" },
        { slug: "distraction", label: "My phone eats my day", emoji: "📱" },
        { slug: "motivation", label: "I start strong, then stop", emoji: "🔁" },
        { slug: "overwhelm", label: "I get overwhelmed", emoji: "🌀" },
        { slug: "self-doubt", label: "I doubt myself", emoji: "🪞" },
        { slug: "no-plan", label: "I don't have a clear plan", emoji: "🗺️" },
      ],
      skippable: true,
      modelKey: "obstacles",
    },
    {
      id: "system-interstitial",
      type: "info",
      headline:
        "Consistency isn't a personality trait. It's a system — and you're about to build one.",
      cta: "Continue",
    },
    {
      id: "results-preframe",
      type: "info",
      headline:
        "A few minutes a day is all it takes. Give it a couple of weeks.",
      cta: "Continue",
    },
    {
      id: "time-devotion",
      type: "single",
      headline: "How much time will you give your future self each day?",
      sub: "Small and daily beats big and rare",
      options: [
        { slug: "1", label: "1 minute a day" },
        { slug: "3", label: "3 minutes a day" },
        { slug: "10", label: "10 minutes a day" },
      ],
      skippable: true,
      modelKey: "raw.daily_minutes",
    },
    {
      id: "streak-goal",
      type: "single",
      headline: "What goal do you want to start with?",
      sub: "Pick what feels doable — your streak keeps counting either way",
      options: [
        { slug: "3", label: "3 days in a row" },
        { slug: "7", label: "7 days in a row" },
        { slug: "21", label: "21 days in a row" },
      ],
      skippable: true,
      modelKey: "raw.streak_goal",
    },
    {
      id: "streak",
      type: "streak-commit",
      headline: "Three small readings a day. That's the whole ask.",
      sub: "Read any 3 quotes or affirmations and the day counts. Miss a day, the chain breaks.",
      lines: [
        "Days 1–3 · Novelty carries you. Everyone survives this part.",
        "Days 4–14 · The dip. Motivation fades before results show — this is where most people quit.",
        "Days 15–21 · It stops being effort. The reading finds you, not the other way around.",
      ],
      info: "Most habit research puts the first real foothold around three weeks of daily reps.",
      // Echoes the goal picked one screen earlier; 21 when it was skipped.
      cta: (ctx) => `I'm in for ${ctx.answers["raw.streak_goal"] ?? "21"} days`,
      modelKey: "raw.streak_goal",
    },
    {
      id: "traits",
      type: "chips",
      headline: "Meet your future self. What are they like?",
      sub: "Pick the traits you're building toward",
      maxSelect: 4,
      minSelect: 1,
      options: [
        { slug: "disciplined", label: "Disciplined" },
        { slug: "confident", label: "Confident" },
        { slug: "calm", label: "Calm" },
        { slug: "strong", label: "Strong" },
        { slug: "focused", label: "Focused" },
        { slug: "free", label: "Free" },
        { slug: "generous", label: "Generous" },
        { slug: "fulfilled", label: "Fulfilled" },
      ],
      skippable: true,
      modelKey: "future_traits",
    },
    {
      id: "vision",
      type: "single",
      headline: "Do you have a clear vision of the life you want?",
      sub: "Pick the one that feels true",
      options: [
        { slug: "yes", label: "Yes, I do" },
        { slug: "working", label: "I'm working on it" },
        { slug: "day-by-day", label: "I take it one day at a time" },
        { slug: "no", label: "Not really" },
      ],
      skippable: true,
      modelKey: "raw.vision",
    },
    {
      id: "belief-manifestation",
      type: "single",
      headline: "Do you believe in the power of manifestation?",
      sub: "Pick the one that feels true",
      options: [
        { slug: "yes", label: "Yes, absolutely" },
        { slug: "curious", label: "Not sure, but I'm curious" },
        { slug: "no", label: "It's not my thing" },
      ],
      skippable: true,
      modelKey: "raw.belief_manifestation",
    },
    {
      id: "belief-thoughts",
      type: "single",
      headline: "Do you believe your thoughts help shape your reality?",
      sub: "Pick the one that feels true",
      options: [
        { slug: "yes", label: "Yes, I've seen it happen" },
        { slug: "open", label: "I'm open to it" },
        { slug: "no", label: "Not really" },
      ],
      skippable: true,
      modelKey: "raw.belief_thoughts",
    },
    {
      id: "belief-rewire",
      type: "single",
      headline: "Did you know affirmations can rewire your brain?",
      sub: "Pick the one that feels true",
      options: [
        { slug: "yes", label: "Yes, I believe that" },
        { slug: "unsure", label: "I've heard of it, but I'm not sure" },
        { slug: "tell-me", label: "I didn't know — tell me more" },
        { slug: "skeptical", label: "I'm skeptical, but open" },
      ],
      skippable: true,
      modelKey: "raw.belief_rewire",
    },
    {
      id: "science",
      type: "info",
      // Claim wording stays inside what the cited papers support.
      headline:
        "Studies show daily self-affirmation boosts self-confidence, resilience and overall well-being.",
      sub: "In brain-imaging studies it activates the brain's reward and self-processing centers — most strongly when people focus on their future selves.",
      footnote:
        "Cohen & Sherman, Annual Review of Psychology (2014) · Cascio et al., Social Cognitive and Affective Neuroscience (2016)",
      cta: "Continue",
    },
    {
      id: "benefits",
      type: "info",
      headline: "The benefits of daily personalized affirmations",
      bullets: [
        "Focus on achieving your goals",
        "Shift negative thoughts",
        "Improve mental health",
      ],
      cta: "Got it",
    },
    {
      id: "quote-topics",
      type: "chips",
      headline: "Which voices push you hardest?",
      sub: "We'll weight your daily quotes toward these",
      minSelect: 1,
      options: [
        { slug: "discipline", label: "Discipline" },
        { slug: "ambition", label: "Ambition" },
        { slug: "courage", label: "Courage" },
        { slug: "stoic-calm", label: "Stoic calm" },
        { slug: "gratitude", label: "Gratitude" },
        { slug: "resilience", label: "Resilience" },
        { slug: "focus", label: "Focus" },
        { slug: "kindness", label: "Kindness" },
      ],
      skippable: true,
      modelKey: "quote_interests",
    },
    {
      id: "affirmation-topics",
      type: "chips",
      headline: "And what do you need to hear more often?",
      sub: "Your affirmations will lean this way",
      minSelect: 1,
      options: [
        { slug: "self-belief", label: "Self-belief" },
        { slug: "calm", label: "Calm under pressure" },
        { slug: "health-body", label: "Health & body" },
        { slug: "abundance", label: "Abundance" },
        { slug: "letting-go", label: "Letting go" },
        { slug: "morning-energy", label: "Morning energy" },
        { slug: "boundaries", label: "Boundaries" },
        { slug: "self-respect", label: "Self-respect" },
      ],
      skippable: true,
      trialCaption: true,
      modelKey: "affirmation_interests",
    },
    {
      id: "practice-mode",
      type: "multi",
      headline: "How would you like to practice with Future Self?",
      sub: "Choose at least one",
      minSelect: 1,
      // No "listening" option: the app has no audio.
      options: [
        { slug: "phone", label: "Reading them on my phone" },
        { slug: "widget", label: "Seeing them on my Home or Lock Screen" },
        { slug: "aloud", label: "Saying them out loud" },
        { slug: "journal", label: "Writing them in a journal" },
        { slug: "post-it", label: "Writing them on a post-it" },
        { slug: "unsure", label: "I'm not sure yet" },
      ],
      skippable: true,
      modelKey: "raw.practice_modes",
    },
    {
      // I Am screen 33: icon picker right before the theme picker. The
      // choice is recorded here and applied once at completion — iOS
      // shows a system alert on every icon change.
      id: "app-icon",
      type: "app-icon",
      headline: "Pick the icon you want to see every day.",
      sub: "This becomes Future Self's icon on your Home Screen — change it anytime.",
      trialCaption: true,
      cta: "Continue",
      modelKey: "raw.app_icon",
    },
    {
      id: "theme",
      type: "theme",
      headline: "Choose how your words should look.",
      sub: "You can change this anytime — or build your own",
      trialCaption: true,
      cta: "Continue",
    },
    {
      id: "life-goal",
      type: "text",
      headline: "Finish the sentence: a year from now, I want to be…",
      sub: "Your words. They'll follow you through the app — and onto your Home Screen if you want.",
      placeholder: "…someone who shows up every single day",
      multiline: true,
      maxLength: 280,
      cta: "Save it",
      skippable: true,
      modelKey: "life_goal",
    },
    {
      id: "achieve",
      type: "multi",
      headline: "What do you want to achieve with Future Self?",
      sub: "Choose at least one",
      minSelect: 1,
      options: [
        { slug: "best-self", label: "Become the best version of myself" },
        { slug: "discipline", label: "Build discipline that lasts" },
        { slug: "confidence", label: "Feel more self-confident" },
        { slug: "mindset", label: "Develop a positive mindset" },
        { slug: "presence", label: "Be more present and enjoy life" },
        { slug: "mental-health", label: "Improve my mental health" },
      ],
      skippable: true,
      // Last question before the result/paywall.
      trialCaption: true,
      modelKey: "raw.outcome_goals",
    },
    {
      id: "result",
      type: "result",
      cta: "Sounds right",
    },
    {
      id: "source",
      type: "single",
      headline: "One last thing — how did you find us?",
      sub: "It helps a small team keep showing up there",
      options: [
        { slug: "web", label: "Web search" },
        { slug: "app-store", label: "App Store" },
        { slug: "friend", label: "Friend or family" },
        { slug: "tiktok", label: "TikTok" },
        { slug: "instagram", label: "Instagram" },
        { slug: "other", label: "Other" },
      ],
      skippable: true,
      modelKey: "raw.source",
    },
    {
      id: "trial-preframe",
      type: "info",
      headline: (ctx) =>
        ctx.trialLength
          ? `Everything unlocked, free for ${ctx.trialLength}.`
          : "Everything unlocked from day one.",
      sub: "No surprises: we'll remind you before the trial ends, and you can cancel anytime.",
      cta: "Show me how it works",
      condition: (ctx) => ctx.trialLength !== null,
    },
    {
      id: "paywall",
      type: "paywall",
    },
    {
      id: "widget-lock",
      type: "widget-promo",
      headline: "Put your future on your Lock Screen.",
      sub: "See your words without unlocking your phone",
      cta: "Got it",
      placeholder: "I will not waste today.",
    },
    {
      id: "widget-home",
      type: "widget-promo",
      headline: "One more: your Home Screen.",
      sub: "Touch and hold your Home Screen, tap Edit, and add Future Self",
      cta: "Got it",
      placeholder: "A year from now, you'll be glad you started today.",
    },
  ],
};
