import type { VariantConfig } from "../engine/types";

/**
 * iam-founder: founder ideas (possibleonboardingcopy.md) on the I Am UX
 * framework. Spec: docs/ONBOARDING_COPY_IAM_FOUNDER.md
 */
export const iamFounder: VariantConfig = {
  id: "iam-founder",
  family: "iam",
  paywallStyle: "timeline",
  paywallCloseDelayMs: 2000,
  authSheetBeforePaywall: true,
  steps: [
    {
      id: "welcome",
      type: "welcome",
      headline: "Hey, it's me. Your future self.",
      sub: "Everything I become starts with what you do today. Keep going.",
      cta: "Keep going",
    },
    {
      id: "qualification",
      type: "info",
      headline: "2 minutes. Honest answers only.",
      sub: "What you tell us shapes every word you'll see.",
      cta: "I'm ready",
    },
    {
      id: "readiness",
      type: "single",
      headline: "Are you ready to change the direction of your life?",
      sub: "There's no wrong answer, only a starting point",
      options: [
        { slug: "waiting", label: "Yes, I've been waiting for this" },
        { slug: "think-so", label: "I think so" },
        { slug: "want-to", label: "I want to be" },
        { slug: "not-sure", label: "I'm not sure yet" },
      ],
      modelKey: "raw.readiness",
    },
    {
      id: "name",
      type: "text",
      headline: "What should your future self call you?",
      sub: "Your name will appear in your daily quotes",
      placeholder: "Your name",
      cta: "Continue",
      skippable: true,
      maxLength: 40,
      modelKey: "name",
    },
    {
      id: "gender",
      type: "single",
      headline: (ctx) =>
        ctx.name
          ? `Which best describes you, ${ctx.name}?`
          : "Which best describes you?",
      sub: "Some quotes and affirmations use your gender",
      options: [
        { slug: "female", label: "Female" },
        { slug: "male", label: "Male" },
        { slug: "non-binary", label: "Non-binary" },
        { slug: "na", label: "Prefer not to say" },
      ],
      skippable: true,
      modelKey: "gender",
    },
    {
      id: "motivation",
      type: "single",
      headline: "How motivated are you to make a change right now?",
      sub: "Your answer sets the tone of your daily mix",
      options: [
        { slug: "everything", label: "I'm ready to give it everything" },
        {
          slug: "inconsistent",
          label: "I'm motivated, but I need help staying consistent",
        },
        { slug: "stuck", label: "I want to change, but I feel stuck" },
        { slug: "figuring-out", label: "I'm still figuring out what I want" },
        { slug: "exploring", label: "I'm mostly exploring for now" },
      ],
      modelKey: "motivation_level",
    },
    {
      id: "quote-interstitial",
      type: "info",
      headline:
        "The reason you want it so badly is because your Future Self already has it.",
      cta: "Continue",
    },
    {
      id: "areas",
      type: "multi",
      headline: "What should Future Self help you with most?",
      sub: "Choose up to 3. They shape your daily quotes",
      minSelect: 1,
      maxSelect: 3,
      options: [
        { slug: "body", label: "Taking care of my body", emoji: "🩺" },
        {
          slug: "career",
          label: "Building my career or business",
          emoji: "💼",
        },
        { slug: "money", label: "Becoming financially secure", emoji: "💰" },
        { slug: "focus", label: "Staying focused and consistent", emoji: "🎯" },
        { slug: "peace", label: "Feeling confident and at peace", emoji: "🕊️" },
        {
          slug: "relationships",
          label: "Strengthening my relationships",
          emoji: "❤️",
        },
        { slug: "other", label: "Something else", emoji: "✨" },
      ],
      skippable: true,
      modelKey: "primary_goals",
    },
    {
      id: "obstacles",
      type: "multi",
      headline: "What gets in the way of your progress most often?",
      sub: "Naming it is half the fight",
      minSelect: 1,
      options: [
        { slug: "procrastination", label: "I procrastinate" },
        { slug: "distraction", label: "I get distracted" },
        { slug: "motivation", label: "I lose motivation" },
        { slug: "overwhelm", label: "I feel overwhelmed" },
        { slug: "self-doubt", label: "I doubt myself" },
        { slug: "no-plan", label: "I don't know where to start" },
        {
          slug: "on-track",
          label: "I'm making progress, I want help staying on track",
        },
      ],
      skippable: true,
      modelKey: "obstacles",
    },
    {
      id: "mechanism",
      type: "info",
      headline: "Future Self was built for exactly that.",
      sub: "The right quotes, arriving at the right moments, until showing up becomes who you are. Small pushes, every day: that's the whole method, and it's why the app exists.",
      cta: "Show me",
    },
    {
      id: "traits",
      type: "chips",
      headline: "Select 3 characteristics of your future self.",
      sub: "This is who we're building",
      minSelect: 3,
      maxSelect: 3,
      options: [
        { slug: "disciplined", label: "Disciplined" },
        { slug: "confident", label: "Confident" },
        { slug: "calm", label: "Calm" },
        { slug: "healthy", label: "Healthy" },
        { slug: "wealthy", label: "Wealthy" },
        { slug: "focused", label: "Focused" },
        { slug: "resilient", label: "Resilient" },
        { slug: "loved", label: "Loved" },
      ],
      modelKey: "future_traits",
    },
    {
      id: "notifications",
      type: "notifications",
      headline: "Your future self will check in during the day.",
      sub: "A few of the right quotes, spread through your day. You decide how often, and when.",
      cta: "Turn on reminders",
      mockLine: "You said you were ready. Prove it for 5 minutes.",
    },
    {
      id: "streak",
      type: "streak-commit",
      headline: "Show up for 3 quotes a day.",
      sub: "Read any 3 quotes or affirmations and the day counts. Your future self keeps score.",
      lines: [
        "Days 1 to 3 · Momentum does the lifting. Enjoy it.",
        "Days 4 to 14 · The dip. This is where the old you argues back, and where most people fold.",
        "Days 15 to 21 · The reps take over. Showing up stops being a decision.",
      ],
      info: "Habit research says the early weeks are the hardest part. Keep the reps small and daily.",
      cta: "I'm in for 21 days",
      modelKey: "raw.streak_goal",
    },
    {
      id: "affirmation-topics",
      type: "chips",
      headline: "What do you need to hear more often?",
      sub: "Your affirmations will lean this way",
      minSelect: 1,
      options: [
        { slug: "self-belief", label: "Self-belief" },
        { slug: "discipline", label: "Discipline" },
        { slug: "calm", label: "Calm" },
        { slug: "health-body", label: "Health & body" },
        { slug: "abundance", label: "Abundance" },
        { slug: "confidence", label: "Confidence" },
        { slug: "letting-go", label: "Letting go" },
        { slug: "gratitude", label: "Gratitude" },
      ],
      skippable: true,
      trialCaption: true,
      modelKey: "affirmation_interests",
    },
    {
      // I Am screen 33: icon picker right before the theme picker.
      // Recorded here, applied once at completion (iOS alerts on change).
      id: "app-icon",
      type: "app-icon",
      headline: "Which icon should I wear on your Home Screen?",
      sub: "You'll see it every day. Change it whenever you like.",
      trialCaption: true,
      cta: "Continue",
      modelKey: "raw.app_icon",
    },
    {
      id: "theme",
      type: "theme",
      headline: "Choose how your daily quotes should look.",
      sub: "Change it anytime",
      trialCaption: true,
      cta: "Continue",
    },
    {
      id: "result",
      type: "result",
      cta: "See my plan",
    },
    {
      id: "trial-preframe",
      type: "info",
      headline: (ctx) =>
        ctx.trialLength
          ? `Everything unlocked, free for ${ctx.trialLength}.`
          : "Everything unlocked from day one.",
      sub: "We'll remind you before it ends. No surprises, no pressure. Cancel anytime.",
      cta: "How it works",
      condition: (ctx) => ctx.trialLength !== null,
    },
    {
      id: "save-account",
      type: "auth-sheet",
      headline: "Create your account",
      sub: "Sign in with Apple, Google, or email. Then you can start your trial.",
      condition: (ctx) => ctx.isAnonymous,
    },
    {
      id: "paywall",
      type: "paywall",
    },
    {
      id: "widget-lock",
      type: "widget-promo",
      headline: "Keep me on your Lock Screen.",
      sub: "Your quotes, visible without unlocking your phone",
      cta: "Got it",
      placeholder: "Everything I become starts with what you do today.",
    },
    {
      id: "widget-home",
      type: "widget-promo",
      headline: "And one for your Home Screen.",
      sub: "Touch and hold your Home Screen, tap Edit, add Future Self",
      cta: "Got it",
      placeholder:
        "The reason you want it so badly is because your Future Self already has it.",
    },
  ],
};
