-- Seed content library for Future Self: motivational quotes + affirmations.
-- Public-domain quotes carry real attributions (authors long deceased / clearly public-domain texts);
-- all unattributed rows (author IS NULL) are original lines written for this app.

INSERT INTO public.content_items (type, body, author, categories, tags, priority, notification_eligible) VALUES
('quote', 'Confine yourself to the present.', 'Marcus Aurelius', ARRAY['focus','stoic-calm']::text[], ARRAY['goal:focus','obstacle:distraction','trait:focused']::text[], 0, true),
('quote', 'The best revenge is to be unlike him who performed the injury.', 'Marcus Aurelius', ARRAY['kindness','stoic-calm']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('quote', 'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.', 'Marcus Aurelius', ARRAY['stoic-calm','gratitude']::text[], ARRAY['goal:peace','trait:calm','trait:fulfilled']::text[], 0, true),
('quote', 'If it is not right, do not do it; if it is not true, do not say it.', 'Marcus Aurelius', ARRAY['discipline']::text[], ARRAY['trait:disciplined','trait:strong']::text[], 0, true),
('quote', 'Think not so much of what you have not as of what you have.', 'Marcus Aurelius', ARRAY['gratitude','stoic-calm']::text[], ARRAY['goal:peace','trait:fulfilled']::text[], 0, true),
('quote', 'Difficulties strengthen the mind, as labor does the body.', 'Seneca', ARRAY['resilience']::text[], ARRAY['trait:resilient','trait:strong','goal:body']::text[], 0, true),
('quote', 'He who is brave is free.', 'Seneca', ARRAY['courage']::text[], ARRAY['trait:free','trait:strong']::text[], 0, true),
('quote', 'Begin at once to live, and count each separate day as a separate life.', 'Seneca', ARRAY['stoic-calm','ambition']::text[], ARRAY['goal:peace','obstacle:procrastination']::text[], 0, true),
('quote', 'No man was ever wise by chance.', 'Seneca', ARRAY['discipline','focus']::text[], ARRAY['trait:disciplined','obstacle:no-plan']::text[], 0, true),
('quote', 'We suffer more often in imagination than in reality.', 'Seneca', ARRAY['stoic-calm','resilience']::text[], ARRAY['obstacle:overwhelm','goal:peace','trait:calm']::text[], 0, true),
('quote', 'Men are disturbed not by the things which happen, but by their opinions about them.', 'Epictetus', ARRAY['stoic-calm']::text[], ARRAY['goal:peace','obstacle:overwhelm','trait:calm']::text[], 0, true),
('quote', 'No man is free who is not master of himself.', 'Epictetus', ARRAY['discipline','stoic-calm']::text[], ARRAY['trait:disciplined','trait:free']::text[], 0, true),
('quote', 'First say to yourself what you would be; and then do what you have to do.', 'Epictetus', ARRAY['ambition','discipline']::text[], ARRAY['obstacle:no-plan','goal:career']::text[], 0, true),
('quote', 'Make the best use of what is in your power, and take the rest as it happens.', 'Epictetus', ARRAY['stoic-calm','resilience']::text[], ARRAY['goal:peace','trait:calm','obstacle:overwhelm']::text[], 0, true),
('quote', 'Wealth consists not in having great possessions, but in having few wants.', 'Epictetus', ARRAY['gratitude','stoic-calm']::text[], ARRAY['goal:money','trait:fulfilled']::text[], 0, true),
('quote', 'He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.', 'Epictetus', ARRAY['gratitude']::text[], ARRAY['trait:fulfilled','goal:peace']::text[], 0, true),
('quote', 'A journey of a thousand miles begins with a single step.', 'Lao Tzu', ARRAY['ambition','courage']::text[], ARRAY['obstacle:procrastination','obstacle:overwhelm','obstacle:no-plan']::text[], 0, true),
('quote', 'He who conquers others is strong; he who conquers himself is mighty.', 'Lao Tzu', ARRAY['discipline']::text[], ARRAY['trait:disciplined','trait:strong']::text[], 0, true),
('quote', 'To see what is right and not to do it is want of courage.', 'Confucius', ARRAY['courage']::text[], ARRAY['trait:strong','trait:kind']::text[], 0, true),
('quote', 'What you do not want done to yourself, do not do to others.', 'Confucius', ARRAY['kindness']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('quote', 'Well done is better than well said.', 'Benjamin Franklin', ARRAY['discipline']::text[], ARRAY['obstacle:procrastination','trait:disciplined']::text[], 0, true),
('quote', 'Lost time is never found again.', 'Benjamin Franklin', ARRAY['focus','discipline']::text[], ARRAY['obstacle:procrastination','obstacle:distraction','goal:focus']::text[], 0, true),
('quote', 'Little strokes fell great oaks.', 'Benjamin Franklin', ARRAY['resilience','discipline']::text[], ARRAY['obstacle:overwhelm','trait:resilient']::text[], 0, true),
('quote', 'Diligence is the mother of good luck.', 'Benjamin Franklin', ARRAY['discipline','ambition']::text[], ARRAY['trait:disciplined','goal:money']::text[], 0, true),
('quote', 'Self-trust is the first secret of success.', 'Ralph Waldo Emerson', ARRAY['ambition','courage']::text[], ARRAY['obstacle:self-doubt','trait:confident','goal:career']::text[], 0, true),
('quote', 'The reward of a thing well done is to have done it.', 'Ralph Waldo Emerson', ARRAY['discipline','gratitude']::text[], ARRAY['trait:fulfilled','goal:career']::text[], 0, true),
('quote', 'Do the thing, and you shall have the power.', 'Ralph Waldo Emerson', ARRAY['courage','ambition']::text[], ARRAY['obstacle:procrastination','obstacle:motivation','trait:confident']::text[], 0, true),
('quote', 'Nothing great was ever achieved without enthusiasm.', 'Ralph Waldo Emerson', ARRAY['ambition']::text[], ARRAY['obstacle:motivation','goal:career']::text[], 0, true),
('quote', 'If one advances confidently in the direction of his dreams, and endeavors to live the life which he has imagined, he will meet with a success unexpected in common hours.', 'Henry David Thoreau', ARRAY['ambition','courage']::text[], ARRAY['goal:career','trait:confident','obstacle:self-doubt']::text[], 10, false),
('quote', 'It is not enough to be industrious; so are the ants. What are you industrious about?', 'Henry David Thoreau', ARRAY['focus']::text[], ARRAY['goal:focus','obstacle:distraction','obstacle:no-plan']::text[], 0, true),
('quote', 'Obstacles cannot crush me; every obstacle yields to stern resolve.', 'Leonardo da Vinci', ARRAY['resilience','courage']::text[], ARRAY['trait:resilient','trait:strong','obstacle:motivation']::text[], 0, true),
('quote', 'One can have no smaller or greater mastery than mastery of oneself.', 'Leonardo da Vinci', ARRAY['discipline']::text[], ARRAY['trait:disciplined','trait:strong']::text[], 0, true),
('quote', 'The things we have to learn before we can do them, we learn by doing them.', 'Aristotle', ARRAY['ambition','courage']::text[], ARRAY['obstacle:no-plan','obstacle:self-doubt','goal:career']::text[], 0, true),
('quote', 'No one knows what he can do till he tries.', 'Publilius Syrus', ARRAY['courage','ambition']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 0, true),
('quote', 'To do two things at once is to do neither.', 'Publilius Syrus', ARRAY['focus']::text[], ARRAY['goal:focus','obstacle:distraction']::text[], 0, true),
('quote', 'Would you have a great empire? Rule over yourself.', 'Publilius Syrus', ARRAY['discipline','stoic-calm']::text[], ARRAY['trait:disciplined','trait:free']::text[], 0, true),
('quote', 'You are today where your thoughts have brought you; you will be tomorrow where your thoughts take you.', 'James Allen', ARRAY['focus','ambition']::text[], ARRAY['goal:focus','trait:focused']::text[], 10, true),
('quote', 'Circumstance does not make the man; it reveals him to himself.', 'James Allen', ARRAY['resilience','stoic-calm']::text[], ARRAY['trait:resilient']::text[], 0, true),
('quote', 'Calmness of mind is one of the beautiful jewels of wisdom.', 'James Allen', ARRAY['stoic-calm']::text[], ARRAY['goal:peace','trait:calm']::text[], 0, true),
('quote', 'It is hard to fail, but it is worse never to have tried to succeed.', 'Theodore Roosevelt', ARRAY['courage','resilience']::text[], ARRAY['obstacle:self-doubt','trait:resilient']::text[], 0, true),
('quote', 'It is not the critic who counts; the credit belongs to the man who is actually in the arena.', 'Theodore Roosevelt', ARRAY['courage']::text[], ARRAY['obstacle:self-doubt','trait:confident','trait:strong']::text[], 10, true),
('quote', 'The art of being wise is the art of knowing what to overlook.', 'William James', ARRAY['focus','stoic-calm']::text[], ARRAY['goal:focus','obstacle:distraction','obstacle:overwhelm']::text[], 0, true),
('quote', 'Believe that life is worth living, and your belief will help create the fact.', 'William James', ARRAY['courage','gratitude']::text[], ARRAY['obstacle:self-doubt','goal:peace']::text[], 0, true),
('quote', 'Our greatest glory consists not in never falling, but in rising every time we fall.', 'Oliver Goldsmith', ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:self-doubt']::text[], 10, true),
('quote', 'Courage is resistance to fear, mastery of fear - not absence of fear.', 'Mark Twain', ARRAY['courage']::text[], ARRAY['trait:strong','trait:confident']::text[], 0, true),
('quote', 'If there is no struggle, there is no progress.', 'Frederick Douglass', ARRAY['resilience','courage']::text[], ARRAY['trait:resilient','obstacle:motivation']::text[], 0, true),
('quote', 'Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome while trying to succeed.', 'Booker T. Washington', ARRAY['resilience','ambition']::text[], ARRAY['trait:resilient','goal:career']::text[], 0, false),
('quote', 'Optimism is the faith that leads to achievement; nothing can be done without hope and confidence.', 'Helen Keller', ARRAY['courage','ambition']::text[], ARRAY['trait:confident','obstacle:self-doubt','obstacle:motivation']::text[], 0, true),
('quote', 'No act of kindness, no matter how small, is ever wasted.', 'Aesop', ARRAY['kindness']::text[], ARRAY['trait:kind','trait:generous','goal:relationships']::text[], 0, true),
('quote', 'Gratitude is not only the greatest of virtues, but the parent of all the others.', 'Cicero', ARRAY['gratitude','kindness']::text[], ARRAY['trait:fulfilled','goal:relationships']::text[], 0, true),
('quote', 'He who fears he shall suffer, already suffers what he fears.', 'Michel de Montaigne', ARRAY['stoic-calm']::text[], ARRAY['obstacle:overwhelm','goal:peace','trait:calm']::text[], 0, true),
('quote', 'Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt.', 'William Shakespeare', ARRAY['courage']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 10, true),
('quote', 'He who has begun is half done; dare to be wise, and begin.', 'Horace', ARRAY['courage','ambition']::text[], ARRAY['obstacle:procrastination','obstacle:no-plan']::text[], 10, true),
('quote', 'Perseverance is a great element of success. If you only knock long enough and loud enough at the gate, you are sure to wake up somebody.', 'Henry Wadsworth Longfellow', ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:motivation']::text[], 0, true),
('quote', 'I am the master of my fate; I am the captain of my soul.', 'William Ernest Henley', ARRAY['courage','resilience']::text[], ARRAY['trait:strong','trait:free']::text[], 10, true),
('quote', 'Motivation gets you to the door. Habit walks you through it.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:motivation','trait:disciplined']::text[], 0, true),
('quote', 'You don''t need a better plan. You need a kept promise.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:no-plan','trait:disciplined']::text[], 0, true),
('quote', 'Skipped days teach your goals not to trust you.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:procrastination','obstacle:motivation']::text[], 0, true),
('quote', 'When mood and standard disagree, let the standard win.', NULL, ARRAY['discipline']::text[], ARRAY['trait:disciplined','obstacle:motivation']::text[], 0, true),
('quote', 'Small boring reps build big loud results.', NULL, ARRAY['discipline','ambition']::text[], ARRAY['trait:disciplined','goal:body']::text[], 0, true),
('quote', 'Your future is drafted in your routines and edited by your choices.', NULL, ARRAY['discipline']::text[], ARRAY['trait:disciplined','obstacle:no-plan']::text[], 0, true),
('quote', 'Tired counts. Doubtful counts. Showing up still counts double.', NULL, ARRAY['discipline','resilience']::text[], ARRAY['obstacle:motivation','trait:resilient']::text[], 0, true),
('quote', 'A rule you keep is worth ten goals you admire.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:no-plan','trait:disciplined']::text[], 0, true),
('quote', 'Consistency is the rarest talent, and anyone can have it.', NULL, ARRAY['discipline']::text[], ARRAY['trait:disciplined','obstacle:motivation']::text[], 0, true),
('quote', 'Make the habit easy to start and hard to argue with.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:procrastination','obstacle:no-plan']::text[], 0, true),
('quote', 'Nobody is coming to do the reps for you.', NULL, ARRAY['discipline','courage']::text[], ARRAY['obstacle:procrastination','trait:strong','goal:body']::text[], 0, true),
('quote', 'Win the small hours and the big years take care of themselves.', NULL, ARRAY['discipline']::text[], ARRAY['trait:disciplined','goal:career']::text[], 0, true),
('quote', 'Attention is a budget. Spend it where returns live.', NULL, ARRAY['focus']::text[], ARRAY['goal:focus','obstacle:distraction']::text[], 0, true),
('quote', 'One task, fully faced, beats ten tasks half-touched.', NULL, ARRAY['focus']::text[], ARRAY['goal:focus','obstacle:overwhelm','obstacle:distraction']::text[], 0, true),
('quote', 'Your phone can wait. Your potential is on a timer.', NULL, ARRAY['focus']::text[], ARRAY['obstacle:distraction','goal:focus']::text[], 0, true),
('quote', 'Distraction is a tax you can stop paying anytime.', NULL, ARRAY['focus']::text[], ARRAY['obstacle:distraction','trait:focused']::text[], 0, true),
('quote', 'Protect one deep hour and the shallow ones behave.', NULL, ARRAY['focus']::text[], ARRAY['goal:focus','obstacle:distraction','trait:focused']::text[], 0, true),
('quote', 'What you ignore on purpose is a decision, not a loss.', NULL, ARRAY['focus','stoic-calm']::text[], ARRAY['goal:focus','obstacle:overwhelm']::text[], 0, true),
('quote', 'Multitasking is just interrupting yourself with extra steps.', NULL, ARRAY['focus']::text[], ARRAY['obstacle:distraction','goal:focus']::text[], 0, true),
('quote', 'Focus is what remains after you subtract the noise.', NULL, ARRAY['focus']::text[], ARRAY['goal:focus','trait:focused']::text[], 0, true),
('quote', 'Aim narrow, hit deep.', NULL, ARRAY['focus','ambition']::text[], ARRAY['goal:focus','trait:focused']::text[], 0, true),
('quote', 'Write down the one thing today is for, then defend it.', NULL, ARRAY['focus','discipline']::text[], ARRAY['obstacle:no-plan','goal:focus','obstacle:distraction']::text[], 0, true),
('quote', 'Noise is endless; give your attention a shorter guest list.', NULL, ARRAY['focus']::text[], ARRAY['obstacle:distraction','obstacle:overwhelm']::text[], 0, true),
('quote', 'Finish the thought. Finish the set. Finish the day.', NULL, ARRAY['focus','discipline']::text[], ARRAY['trait:focused','goal:body']::text[], 0, true),
('quote', 'Being right feels good for a minute; being kind lasts all day.', NULL, ARRAY['kindness']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('quote', 'Kindness is strength that chose gentleness on purpose.', NULL, ARRAY['kindness']::text[], ARRAY['trait:kind','trait:strong']::text[], 0, true),
('quote', 'Make your presence a place people can rest.', NULL, ARRAY['kindness']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('quote', 'Generosity compounds faster than any account you own.', NULL, ARRAY['kindness']::text[], ARRAY['trait:generous','goal:money']::text[], 0, true),
('quote', 'The softest word in the room often carries the most weight.', NULL, ARRAY['kindness']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('quote', 'You never shrink by helping someone else stand taller.', NULL, ARRAY['kindness']::text[], ARRAY['trait:generous','goal:relationships']::text[], 0, true),
('quote', 'Patience with people is kindness wearing work clothes.', NULL, ARRAY['kindness']::text[], ARRAY['trait:kind','trait:calm','goal:relationships']::text[], 0, true),
('quote', 'It takes muscle to stay soft in a hard week.', NULL, ARRAY['kindness','resilience']::text[], ARRAY['trait:kind','trait:strong']::text[], 0, true),
('quote', 'Talk about absent people as if they can hear you.', NULL, ARRAY['kindness']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('quote', 'A small kindness done today outruns a grand intention kept for someday.', NULL, ARRAY['kindness']::text[], ARRAY['trait:kind','trait:generous','obstacle:procrastination']::text[], 0, true),
('quote', 'Count your wins before you count your worries.', NULL, ARRAY['gratitude']::text[], ARRAY['goal:peace','obstacle:overwhelm']::text[], 0, true),
('quote', 'Gratitude turns an ordinary Tuesday into enough.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:fulfilled','goal:peace']::text[], 0, true),
('quote', 'What you appreciate, you start to actually see.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:fulfilled']::text[], 0, true),
('quote', 'Envy inventories other people''s lives; gratitude audits your own.', NULL, ARRAY['gratitude']::text[], ARRAY['goal:peace','trait:fulfilled']::text[], 0, true),
('quote', 'A thankful mind has fewer emergencies.', NULL, ARRAY['gratitude','stoic-calm']::text[], ARRAY['goal:peace','trait:calm']::text[], 0, true),
('quote', 'Some of what you have today was once the whole wish list.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:fulfilled','goal:peace']::text[], 0, true),
('quote', 'Say thank you like you mean it, then act like it too.', NULL, ARRAY['gratitude','kindness']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('quote', 'Gratitude doesn''t cancel ambition; it funds it.', NULL, ARRAY['gratitude','ambition']::text[], ARRAY['obstacle:motivation','trait:fulfilled']::text[], 0, true),
('quote', 'The good you notice grows; the good you ignore leaves quietly.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:fulfilled','goal:peace']::text[], 0, true),
('quote', 'Falling is data. Staying down is a decision.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:self-doubt']::text[], 0, true),
('quote', 'Every scar on your plan is proof you kept going.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:no-plan']::text[], 0, true),
('quote', 'Storms pass faster when you keep walking.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:overwhelm']::text[], 0, true),
('quote', 'Setbacks are tuition. Learn like you paid full price.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:self-doubt']::text[], 10, true),
('quote', 'What bends without quitting eventually outlasts what breaks.', NULL, ARRAY['resilience','stoic-calm']::text[], ARRAY['trait:resilient','trait:calm']::text[], 0, true),
('quote', 'Hard seasons build the roots that easy ones can''t.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','trait:strong']::text[], 0, true),
('quote', 'Beginning again is a skill, and you are getting good at it.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:motivation']::text[], 0, true),
('quote', 'The comeback doesn''t need an audience to begin.', NULL, ARRAY['resilience','courage']::text[], ARRAY['trait:resilient','obstacle:self-doubt']::text[], 0, true),
('quote', 'A bruised week is not a broken life.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:overwhelm','goal:peace']::text[], 0, true),
('quote', 'Resilience is ordinary effort, repeated on unreasonable days.', NULL, ARRAY['resilience']::text[], ARRAY['trait:resilient','obstacle:motivation']::text[], 0, true),
('quote', 'Big dreams still travel one calendar square at a time.', NULL, ARRAY['ambition']::text[], ARRAY['goal:career','obstacle:overwhelm','obstacle:no-plan']::text[], 0, true),
('quote', 'Your goals don''t need more hype; they need a start time.', NULL, ARRAY['ambition','discipline']::text[], ARRAY['obstacle:procrastination','obstacle:no-plan']::text[], 10, true),
('quote', 'Ambition without a schedule is just a mood.', NULL, ARRAY['ambition','discipline']::text[], ARRAY['obstacle:no-plan','goal:career']::text[], 0, true),
('quote', 'Build the thing you keep waiting for someone else to build.', NULL, ARRAY['ambition','courage']::text[], ARRAY['goal:career','obstacle:procrastination']::text[], 0, true),
('quote', 'Ask bigger questions than your comfort zone can answer.', NULL, ARRAY['ambition']::text[], ARRAY['goal:career','trait:confident']::text[], 0, true),
('quote', 'The future you''re waiting for is waiting on your first move.', NULL, ARRAY['ambition']::text[], ARRAY['obstacle:procrastination','obstacle:motivation']::text[], 0, true),
('quote', 'Outgrow your excuses before you outgrow your chances.', NULL, ARRAY['ambition']::text[], ARRAY['obstacle:motivation','obstacle:procrastination']::text[], 0, true),
('quote', 'Great lives are built out of unglamorous afternoons.', NULL, ARRAY['ambition','discipline']::text[], ARRAY['goal:career','trait:disciplined']::text[], 0, true),
('quote', 'Fear knocks loudest at doors you''re meant to open.', NULL, ARRAY['courage']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 0, true),
('quote', 'Being scared and starting anyway is the whole trick.', NULL, ARRAY['courage']::text[], ARRAY['obstacle:self-doubt','trait:strong']::text[], 0, true),
('quote', 'Sometimes courage is just sending the message you keep re-reading.', NULL, ARRAY['courage']::text[], ARRAY['obstacle:self-doubt','goal:relationships','obstacle:procrastination']::text[], 0, true),
('quote', 'The brave version of you is one honest sentence away.', NULL, ARRAY['courage']::text[], ARRAY['trait:confident','goal:relationships']::text[], 0, true),
('quote', 'Do the thing that makes your excuses nervous.', NULL, ARRAY['courage','ambition']::text[], ARRAY['obstacle:procrastination','obstacle:motivation']::text[], 10, true),
('quote', 'On the other side of awkward is almost everything you want.', NULL, ARRAY['courage']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 0, true),
('quote', 'Control what you can, release the rest, repeat as needed.', NULL, ARRAY['stoic-calm']::text[], ARRAY['goal:peace','obstacle:overwhelm','trait:calm']::text[], 0, true),
('quote', 'An unbothered mind gets more done than an anxious one.', NULL, ARRAY['stoic-calm','focus']::text[], ARRAY['trait:calm','goal:focus']::text[], 0, true),
('quote', 'Few regrets ever followed a slower breath.', NULL, ARRAY['stoic-calm']::text[], ARRAY['trait:calm','goal:peace']::text[], 0, true),
('quote', 'Calm is not where you go; it''s how you travel.', NULL, ARRAY['stoic-calm']::text[], ARRAY['goal:peace','trait:calm']::text[], 0, true),
('quote', 'Not every thought deserves a meeting.', NULL, ARRAY['stoic-calm']::text[], ARRAY['obstacle:overwhelm','trait:calm','obstacle:distraction']::text[], 10, true),
('quote', 'Let it be difficult without letting it be a disaster.', NULL, ARRAY['stoic-calm']::text[], ARRAY['obstacle:overwhelm','trait:calm']::text[], 0, true),
('quote', 'Today only asks for today.', NULL, ARRAY['stoic-calm']::text[], ARRAY['goal:peace','obstacle:overwhelm']::text[], 0, true),
('quote', 'Stillness is a skill; practice it before you need it.', NULL, ARRAY['stoic-calm']::text[], ARRAY['trait:calm','goal:peace']::text[], 0, true),
('affirmation', 'I trust myself to figure things out as I go.', NULL, ARRAY['self-belief']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 0, true),
('affirmation', 'I am becoming the person I said I would be.', NULL, ARRAY['self-belief']::text[], ARRAY['trait:disciplined','goal:career']::text[], 0, true),
('affirmation', 'I back myself, even when the path is unclear.', NULL, ARRAY['self-belief','confidence']::text[], ARRAY['obstacle:self-doubt','obstacle:no-plan']::text[], 0, true),
('affirmation', 'My belief in myself grows with every promise I keep.', NULL, ARRAY['self-belief','discipline']::text[], ARRAY['trait:disciplined','obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I am capable of far more than I give myself credit for.', NULL, ARRAY['self-belief']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 0, true),
('affirmation', 'I trust the quiet voice that says I can.', NULL, ARRAY['self-belief','calm']::text[], ARRAY['obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I have handled hard things before, and I will again.', NULL, ARRAY['self-belief']::text[], ARRAY['trait:resilient','trait:strong']::text[], 0, true),
('affirmation', 'I believe in my ability to learn anything I need.', NULL, ARRAY['self-belief']::text[], ARRAY['goal:career','trait:confident']::text[], 0, true),
('affirmation', 'I am the kind of person who follows through.', NULL, ARRAY['self-belief','discipline']::text[], ARRAY['trait:disciplined','obstacle:procrastination']::text[], 0, true),
('affirmation', 'My doubts are visitors; my belief is the resident.', NULL, ARRAY['self-belief']::text[], ARRAY['obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I choose to bet on myself today.', NULL, ARRAY['self-belief','confidence']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 0, true),
('affirmation', 'I am proof of my own progress.', NULL, ARRAY['self-belief','gratitude']::text[], ARRAY['trait:fulfilled']::text[], 0, true),
('affirmation', 'I do the hard thing first, and the day gets lighter.', NULL, ARRAY['discipline','morning-energy']::text[], ARRAY['obstacle:procrastination','trait:disciplined','goal:focus']::text[], 0, true),
('affirmation', 'I keep promises to myself, especially the small ones.', NULL, ARRAY['discipline','self-respect']::text[], ARRAY['trait:disciplined']::text[], 10, true),
('affirmation', 'I show up on the days I don''t feel like it.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:motivation','trait:disciplined']::text[], 0, true),
('affirmation', 'I trade the easy now for the proud later.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:procrastination','trait:disciplined']::text[], 0, true),
('affirmation', 'My routines carry me on days when motivation cannot.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:motivation','trait:disciplined']::text[], 0, true),
('affirmation', 'I finish what I start, one small step at a time.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:overwhelm','trait:focused']::text[], 0, true),
('affirmation', 'I am consistent, and consistency is my advantage.', NULL, ARRAY['discipline']::text[], ARRAY['trait:disciplined','goal:career']::text[], 0, true),
('affirmation', 'I start before I feel ready, and readiness follows.', NULL, ARRAY['discipline','confidence']::text[], ARRAY['obstacle:procrastination','obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I do today what my future self will thank me for.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:procrastination','goal:money']::text[], 10, true),
('affirmation', 'I am patient with results and relentless with effort.', NULL, ARRAY['discipline']::text[], ARRAY['trait:disciplined','trait:resilient']::text[], 0, true),
('affirmation', 'I make time for what matters instead of waiting for it.', NULL, ARRAY['discipline']::text[], ARRAY['obstacle:procrastination','obstacle:no-plan','goal:focus']::text[], 0, true),
('affirmation', 'I breathe out what I cannot control.', NULL, ARRAY['calm','letting-go']::text[], ARRAY['goal:peace','trait:calm','obstacle:overwhelm']::text[], 0, true),
('affirmation', 'My calm is stronger than this moment''s chaos.', NULL, ARRAY['calm']::text[], ARRAY['goal:peace','trait:calm','obstacle:overwhelm']::text[], 0, true),
('affirmation', 'I move through my day at a steady, unhurried pace.', NULL, ARRAY['calm']::text[], ARRAY['goal:peace','trait:calm']::text[], 0, true),
('affirmation', 'I meet stress with a slow breath and a clear mind.', NULL, ARRAY['calm']::text[], ARRAY['obstacle:overwhelm','trait:calm']::text[], 0, true),
('affirmation', 'My peace is a home I can return to anytime.', NULL, ARRAY['calm']::text[], ARRAY['goal:peace','trait:free']::text[], 0, true),
('affirmation', 'I choose a calm response over a quick reaction.', NULL, ARRAY['calm','self-respect']::text[], ARRAY['trait:calm','goal:relationships']::text[], 0, true),
('affirmation', 'I am safe in this moment, and this moment is enough.', NULL, ARRAY['calm','gratitude']::text[], ARRAY['goal:peace','obstacle:overwhelm']::text[], 0, true),
('affirmation', 'I let my shoulders drop and my thoughts settle.', NULL, ARRAY['calm']::text[], ARRAY['goal:peace','trait:calm']::text[], 0, true),
('affirmation', 'I carry quiet with me into loud places.', NULL, ARRAY['calm']::text[], ARRAY['goal:peace','obstacle:distraction']::text[], 0, true),
('affirmation', 'I do one thing at a time, and that is enough.', NULL, ARRAY['calm','discipline']::text[], ARRAY['obstacle:overwhelm','obstacle:distraction','goal:focus']::text[], 0, true),
('affirmation', 'My mind is clear water; I let the mud settle.', NULL, ARRAY['calm']::text[], ARRAY['goal:peace','trait:calm']::text[], 0, true),
('affirmation', 'I release tension I do not need to carry.', NULL, ARRAY['calm','letting-go']::text[], ARRAY['goal:peace','obstacle:overwhelm']::text[], 0, true),
('affirmation', 'I treat my body like a home I plan to live in.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','trait:healthy']::text[], 0, true),
('affirmation', 'I feel stronger every time I choose to move.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','trait:strong','obstacle:motivation']::text[], 0, true),
('affirmation', 'I fuel my body with what helps it thrive.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','trait:healthy']::text[], 0, true),
('affirmation', 'My body works for me, and I work for my body.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','trait:healthy']::text[], 0, true),
('affirmation', 'I rest well because recovery is part of training.', NULL, ARRAY['health-body','calm']::text[], ARRAY['goal:body','trait:healthy']::text[], 0, true),
('affirmation', 'I enjoy moving my body, and my body rewards me for it.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','obstacle:motivation']::text[], 0, true),
('affirmation', 'I am building a body that carries my ambitions.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','trait:strong']::text[], 0, true),
('affirmation', 'I drink water, I move, I sleep; I keep it simple.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','trait:healthy','obstacle:no-plan']::text[], 0, true),
('affirmation', 'My healthy choices are small deposits that compound daily.', NULL, ARRAY['health-body','abundance']::text[], ARRAY['goal:body','trait:healthy']::text[], 0, true),
('affirmation', 'I listen to my body and give it what it needs.', NULL, ARRAY['health-body']::text[], ARRAY['goal:body','trait:healthy']::text[], 0, true),
('affirmation', 'I am gentle with my body and firm with my habits.', NULL, ARRAY['health-body','discipline']::text[], ARRAY['goal:body','trait:disciplined']::text[], 0, true),
('affirmation', 'I grow stronger, steadier, and more energized each week.', NULL, ARRAY['health-body','morning-energy']::text[], ARRAY['goal:body','trait:strong']::text[], 0, true),
('affirmation', 'I have enough, I do enough, I am enough.', NULL, ARRAY['abundance','self-respect']::text[], ARRAY['trait:fulfilled','goal:peace']::text[], 0, true),
('affirmation', 'I create real value, and money follows it.', NULL, ARRAY['abundance']::text[], ARRAY['goal:money','trait:wealthy']::text[], 0, true),
('affirmation', 'I see opportunity where I used to see obstacles.', NULL, ARRAY['abundance','confidence']::text[], ARRAY['goal:money','trait:confident']::text[], 0, true),
('affirmation', 'My work creates value, and value returns to me.', NULL, ARRAY['abundance']::text[], ARRAY['goal:money','goal:career']::text[], 0, true),
('affirmation', 'I am open to receiving more than I imagined.', NULL, ARRAY['abundance']::text[], ARRAY['trait:wealthy','goal:money']::text[], 0, true),
('affirmation', 'I manage my money with calm and intention.', NULL, ARRAY['abundance','calm']::text[], ARRAY['goal:money','trait:wealthy','obstacle:no-plan']::text[], 0, true),
('affirmation', 'I attract good people, good ideas, and good chances.', NULL, ARRAY['abundance']::text[], ARRAY['goal:relationships','goal:money']::text[], 0, true),
('affirmation', 'My life is rich in the ways that matter most.', NULL, ARRAY['abundance','gratitude']::text[], ARRAY['trait:fulfilled','trait:wealthy']::text[], 0, true),
('affirmation', 'I build wealth patiently, one wise choice at a time.', NULL, ARRAY['abundance']::text[], ARRAY['goal:money','trait:wealthy','trait:disciplined']::text[], 0, true),
('affirmation', 'I celebrate others'' success because there is plenty to go around.', NULL, ARRAY['abundance','gratitude']::text[], ARRAY['trait:generous','goal:money']::text[], 0, true),
('affirmation', 'I turn my skills into security for the people I love.', NULL, ARRAY['abundance']::text[], ARRAY['goal:money','goal:career','trait:wealthy']::text[], 0, true),
('affirmation', 'I am generous, and generosity keeps me rich.', NULL, ARRAY['abundance']::text[], ARRAY['trait:generous','goal:money']::text[], 0, true),
('affirmation', 'I release what I cannot change and act on what I can.', NULL, ARRAY['letting-go','calm']::text[], ARRAY['goal:peace','obstacle:overwhelm','trait:calm']::text[], 0, true),
('affirmation', 'I forgive the past so it stops billing me interest.', NULL, ARRAY['letting-go']::text[], ARRAY['goal:peace','trait:free']::text[], 0, true),
('affirmation', 'I loosen my grip on plans and stay open to better ones.', NULL, ARRAY['letting-go']::text[], ARRAY['trait:free','obstacle:overwhelm']::text[], 0, true),
('affirmation', 'I am not my mistakes; I am what I learned from them.', NULL, ARRAY['letting-go','self-belief']::text[], ARRAY['obstacle:self-doubt','trait:resilient']::text[], 0, true),
('affirmation', 'I drop the weight of opinions that are not mine.', NULL, ARRAY['letting-go','boundaries']::text[], ARRAY['goal:peace','obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I close old tabs in my mind and come back to now.', NULL, ARRAY['letting-go','calm']::text[], ARRAY['obstacle:distraction','goal:focus','goal:peace']::text[], 0, true),
('affirmation', 'I let people be who they are and choose my response.', NULL, ARRAY['letting-go']::text[], ARRAY['goal:relationships','trait:calm']::text[], 0, true),
('affirmation', 'I release the need to be perfect to be worthy.', NULL, ARRAY['letting-go','self-respect']::text[], ARRAY['obstacle:self-doubt','trait:free']::text[], 0, true),
('affirmation', 'I unclench, soften, and start again.', NULL, ARRAY['letting-go','calm']::text[], ARRAY['goal:peace']::text[], 0, true),
('affirmation', 'I leave yesterday where it belongs and travel light today.', NULL, ARRAY['letting-go']::text[], ARRAY['goal:peace','trait:free']::text[], 0, true),
('affirmation', 'I trade resentment for space and grievances for peace.', NULL, ARRAY['letting-go']::text[], ARRAY['goal:peace','goal:relationships']::text[], 0, true),
('affirmation', 'I let go a little more with every breath out.', NULL, ARRAY['letting-go','calm']::text[], ARRAY['goal:peace','trait:calm']::text[], 0, true),
('affirmation', 'I wake up with a purpose bigger than my snooze button.', NULL, ARRAY['morning-energy']::text[], ARRAY['obstacle:procrastination','obstacle:motivation']::text[], 0, true),
('affirmation', 'My morning belongs to me before it belongs to the world.', NULL, ARRAY['morning-energy','boundaries']::text[], ARRAY['goal:focus','obstacle:distraction']::text[], 0, true),
('affirmation', 'I rise, I stretch, I begin; the day follows my lead.', NULL, ARRAY['morning-energy']::text[], ARRAY['trait:disciplined','obstacle:motivation']::text[], 0, true),
('affirmation', 'I greet this morning as a fresh page and write boldly.', NULL, ARRAY['morning-energy']::text[], ARRAY['trait:confident','obstacle:motivation']::text[], 0, true),
('affirmation', 'I open my day with intention before I open my phone.', NULL, ARRAY['morning-energy','discipline']::text[], ARRAY['obstacle:distraction','goal:focus']::text[], 0, true),
('affirmation', 'I begin with a steady breath, a clear head, and ready hands.', NULL, ARRAY['morning-energy']::text[], ARRAY['trait:calm','obstacle:overwhelm']::text[], 0, true),
('affirmation', 'I move first today and let doubt sleep in.', NULL, ARRAY['morning-energy','confidence']::text[], ARRAY['obstacle:self-doubt','obstacle:procrastination']::text[], 0, true),
('affirmation', 'I give the first hour to what matters most.', NULL, ARRAY['morning-energy','discipline']::text[], ARRAY['goal:focus','obstacle:distraction']::text[], 0, true),
('affirmation', 'My best mornings start the night before, and I honor that.', NULL, ARRAY['morning-energy']::text[], ARRAY['trait:disciplined','obstacle:no-plan']::text[], 0, true),
('affirmation', 'I step into today awake, grateful, and slightly unstoppable.', NULL, ARRAY['morning-energy','gratitude']::text[], ARRAY['obstacle:motivation','trait:confident']::text[], 0, true),
('affirmation', 'I make my bed, make my plan, and make my move.', NULL, ARRAY['morning-energy']::text[], ARRAY['obstacle:no-plan','trait:disciplined','obstacle:procrastination']::text[], 0, true),
('affirmation', 'I charge my morning with movement, light, and one clear goal.', NULL, ARRAY['morning-energy','health-body']::text[], ARRAY['goal:body','obstacle:no-plan']::text[], 0, true),
('affirmation', 'I say no without a footnote of guilt.', NULL, ARRAY['boundaries']::text[], ARRAY['goal:relationships','trait:free']::text[], 10, true),
('affirmation', 'I guard my time because it is the one thing I cannot earn back.', NULL, ARRAY['boundaries']::text[], ARRAY['goal:focus','obstacle:distraction']::text[], 0, true),
('affirmation', 'I can love people and still decline their demands.', NULL, ARRAY['boundaries']::text[], ARRAY['goal:relationships','trait:strong']::text[], 0, true),
('affirmation', 'My yes means more because my no is real.', NULL, ARRAY['boundaries','self-respect']::text[], ARRAY['goal:relationships','trait:confident']::text[], 0, true),
('affirmation', 'I end conversations that cost more than they give.', NULL, ARRAY['boundaries']::text[], ARRAY['goal:peace','goal:relationships']::text[], 0, true),
('affirmation', 'I am allowed to rest without earning it first.', NULL, ARRAY['boundaries','letting-go']::text[], ARRAY['obstacle:overwhelm','trait:free']::text[], 0, true),
('affirmation', 'I choose rooms where my energy is respected.', NULL, ARRAY['boundaries','self-respect']::text[], ARRAY['goal:relationships']::text[], 0, true),
('affirmation', 'I set limits calmly and keep them kindly.', NULL, ARRAY['boundaries','calm']::text[], ARRAY['goal:relationships','trait:kind','trait:calm']::text[], 0, true),
('affirmation', 'I take care of myself first, so my care for others is real.', NULL, ARRAY['boundaries']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('affirmation', 'I let calls, requests, and drama wait while I finish what matters.', NULL, ARRAY['boundaries','discipline']::text[], ARRAY['goal:focus','obstacle:distraction']::text[], 0, true),
('affirmation', 'I owe everyone kindness and no one unlimited access.', NULL, ARRAY['boundaries']::text[], ARRAY['goal:relationships','trait:kind','trait:strong']::text[], 0, true),
('affirmation', 'I refuse to say things to myself I would never say to a friend.', NULL, ARRAY['self-respect']::text[], ARRAY['obstacle:self-doubt','trait:kind']::text[], 0, true),
('affirmation', 'I keep my standards even when no one is checking.', NULL, ARRAY['self-respect','discipline']::text[], ARRAY['trait:disciplined']::text[], 0, true),
('affirmation', 'I honor my needs instead of apologizing for them.', NULL, ARRAY['self-respect','boundaries']::text[], ARRAY['goal:relationships','trait:strong']::text[], 0, true),
('affirmation', 'I carry myself like someone worth showing up for.', NULL, ARRAY['self-respect','confidence']::text[], ARRAY['trait:confident']::text[], 0, true),
('affirmation', 'I accept compliments the same way I accept lessons: fully.', NULL, ARRAY['self-respect']::text[], ARRAY['trait:confident','obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I take up the space my life requires.', NULL, ARRAY['self-respect','confidence']::text[], ARRAY['trait:confident','trait:free']::text[], 0, true),
('affirmation', 'I treat my word to myself as my most binding contract.', NULL, ARRAY['self-respect','discipline']::text[], ARRAY['trait:disciplined']::text[], 0, true),
('affirmation', 'I choose respect over approval whenever they compete.', NULL, ARRAY['self-respect']::text[], ARRAY['trait:strong','goal:relationships']::text[], 0, true),
('affirmation', 'I dress, speak, and decide like my opinion of me matters most.', NULL, ARRAY['self-respect']::text[], ARRAY['trait:confident']::text[], 0, true),
('affirmation', 'I ask for what I want in plain language.', NULL, ARRAY['self-respect','boundaries']::text[], ARRAY['goal:relationships','trait:confident']::text[], 0, true),
('affirmation', 'I let my standards, not my moods, run the day.', NULL, ARRAY['self-respect','discipline']::text[], ARRAY['trait:disciplined','obstacle:motivation']::text[], 0, true),
('affirmation', 'I am patient with my progress and proud of my direction.', NULL, ARRAY['self-respect','gratitude']::text[], ARRAY['trait:fulfilled','obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I walk in like I belong, because I do.', NULL, ARRAY['confidence']::text[], ARRAY['trait:confident','obstacle:self-doubt']::text[], 0, true),
('affirmation', 'I speak up while my idea is still warm.', NULL, ARRAY['confidence']::text[], ARRAY['goal:career','trait:confident']::text[], 0, true),
('affirmation', 'I show up as the full version of myself.', NULL, ARRAY['confidence','self-respect']::text[], ARRAY['trait:confident','trait:free']::text[], 0, true),
('affirmation', 'I am comfortable being a beginner in public.', NULL, ARRAY['confidence']::text[], ARRAY['obstacle:self-doubt','trait:confident']::text[], 0, true),
('affirmation', 'I let my work speak, and I am not afraid to translate.', NULL, ARRAY['confidence']::text[], ARRAY['goal:career','trait:confident']::text[], 0, true),
('affirmation', 'I answer self-doubt with evidence: I have done hard things.', NULL, ARRAY['confidence','self-belief']::text[], ARRAY['obstacle:self-doubt','trait:resilient']::text[], 0, true),
('affirmation', 'I bring calm confidence into every room I enter.', NULL, ARRAY['confidence','calm']::text[], ARRAY['trait:confident','trait:calm']::text[], 0, true),
('affirmation', 'I would rather be judged in motion than admired standing still.', NULL, ARRAY['confidence']::text[], ARRAY['obstacle:self-doubt','obstacle:procrastination']::text[], 0, true),
('affirmation', 'I trust my preparation and release the outcome.', NULL, ARRAY['confidence','letting-go']::text[], ARRAY['trait:confident','obstacle:overwhelm']::text[], 0, true),
('affirmation', 'I am allowed to be new at this and still be good at it.', NULL, ARRAY['confidence']::text[], ARRAY['obstacle:self-doubt']::text[], 0, true),
('affirmation', 'My confidence comes from my reps, not my mood.', NULL, ARRAY['confidence','discipline']::text[], ARRAY['trait:confident','trait:disciplined']::text[], 0, true),
('affirmation', 'I have earned the right to speak by doing the work.', NULL, ARRAY['confidence']::text[], ARRAY['trait:confident','goal:career']::text[], 0, true),
('affirmation', 'I notice small good things on purpose.', NULL, ARRAY['gratitude']::text[], ARRAY['goal:peace','trait:fulfilled']::text[], 0, true),
('affirmation', 'I am grateful for a body that tries again every morning.', NULL, ARRAY['gratitude','health-body']::text[], ARRAY['goal:body','trait:healthy']::text[], 0, true),
('affirmation', 'I count what I have before I chase what I want.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:fulfilled','goal:peace']::text[], 10, true),
('affirmation', 'My attention turns toward what is working, and it multiplies.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:fulfilled','obstacle:motivation']::text[], 0, true),
('affirmation', 'I say thank you out loud and mean it.', NULL, ARRAY['gratitude']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('affirmation', 'I find one thing to love about today before noon.', NULL, ARRAY['gratitude','morning-energy']::text[], ARRAY['goal:peace']::text[], 0, true),
('affirmation', 'I treat ordinary days like the gifts they turn out to be.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:fulfilled','goal:peace']::text[], 0, true),
('affirmation', 'I am thankful for the problems that taught me strength.', NULL, ARRAY['gratitude']::text[], ARRAY['trait:resilient','trait:strong']::text[], 0, true),
('affirmation', 'I appreciate the people who stay, and I tell them.', NULL, ARRAY['gratitude']::text[], ARRAY['goal:relationships','trait:kind']::text[], 0, true),
('affirmation', 'My gratitude is louder than my complaints.', NULL, ARRAY['gratitude']::text[], ARRAY['goal:peace','trait:fulfilled']::text[], 0, true),
('affirmation', 'I end my day by naming three things that went right.', NULL, ARRAY['gratitude','calm']::text[], ARRAY['goal:peace']::text[], 0, true),
('affirmation', 'I am wealthy in mornings, friendships, and second chances.', NULL, ARRAY['gratitude','abundance']::text[], ARRAY['trait:wealthy','trait:fulfilled','goal:relationships']::text[], 0, true);

-- Seed counts: 260 rows total = 130 affirmations + 130 quotes
-- (55 public-domain attributed quotes + 75 original unattributed quotes);
-- 15 rows with priority 10; 2 rows with notification_eligible = false (body > 140 chars).
